-- This script was generated by the Schema Diff utility in pgAdmin 4. However there is a chunk that was not generated.
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.
 BEGIN;
 CREATE TABLE IF NOT EXISTS surveys.question_multiple_choice
(
    min_selects integer NOT NULL,
    max_selects integer NOT NULL,
    options integer[] NOT NULL,
    id integer NOT NULL,
    CONSTRAINT question_multiple_choice_pkey PRIMARY KEY (id),
    CONSTRAINT question_multiple_choice_id_fkey FOREIGN KEY (id)
        REFERENCES surveys.questions (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS surveys.question_multiple_choice
    OWNER to wolfy;

GRANT ALL ON TABLE surveys.question_multiple_choice TO wolfy;

GRANT SELECT, DELETE, INSERT, UPDATE ON TABLE surveys.question_multiple_choice TO survey_wolf_bot;

GRANT ALL ON TABLE surveys.question_multiple_choice TO wolfy;
CREATE TABLE IF NOT EXISTS surveys.question_text
(
    min_length integer NOT NULL,
    max_length integer NOT NULL,
    id integer NOT NULL,
    CONSTRAINT question_text_pkey PRIMARY KEY (id),
    CONSTRAINT question_text_id_fkey FOREIGN KEY (id)
        REFERENCES surveys.questions (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS surveys.question_text
    OWNER to wolfy;

GRANT ALL ON TABLE surveys.question_text TO wolfy;

GRANT SELECT, DELETE, INSERT, UPDATE ON TABLE surveys.question_text TO survey_wolf_bot;

GRANT ALL ON TABLE surveys.question_text TO wolfy;
CREATE TABLE IF NOT EXISTS surveys.question_multiple_choice_option
(
    text character varying(80) COLLATE pg_catalog."default" NOT NULL,
    "position" smallint NOT NULL,
    question_id integer NOT NULL,
    CONSTRAINT question_multiple_choice_option_question_id_fkey FOREIGN KEY (question_id)
        REFERENCES surveys.question_multiple_choice (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS surveys.question_multiple_choice_option
    OWNER to wolfy;

GRANT ALL ON TABLE surveys.question_multiple_choice_option TO wolfy;

GRANT SELECT, DELETE, INSERT, UPDATE ON TABLE surveys.question_multiple_choice_option TO survey_wolf_bot;

GRANT ALL ON TABLE surveys.question_multiple_choice_option TO wolfy;

COMMENT ON COLUMN surveys.question_multiple_choice_option."position"
    IS 'This is also the ID of the option as position will be unique.';
CREATE INDEX IF NOT EXISTS fki_question_multiple_choice_option_question_id_fkey
    ON surveys.question_multiple_choice_option USING btree
    (question_id ASC NULLS LAST)
    TABLESPACE pg_default;
CREATE TABLE IF NOT EXISTS surveys.question_datetime
(
    type smallint NOT NULL,
    minimum character varying COLLATE pg_catalog."default" NOT NULL,
    maximum character varying COLLATE pg_catalog."default" NOT NULL,
    id integer NOT NULL,
    CONSTRAINT question_datetime_pkey PRIMARY KEY (id),
    CONSTRAINT question_datetime_id_fkey FOREIGN KEY (id)
        REFERENCES surveys.questions (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS surveys.question_datetime
    OWNER to wolfy;

GRANT ALL ON TABLE surveys.question_datetime TO wolfy;

GRANT SELECT, DELETE, INSERT, UPDATE ON TABLE surveys.question_datetime TO survey_wolf_bot;

GRANT ALL ON TABLE surveys.question_datetime TO wolfy;
CREATE TABLE IF NOT EXISTS surveys.question_response_datetime
(
    response integer NOT NULL,
    "timestamp" character varying COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT question_response_datetime_pkey PRIMARY KEY (response),
    CONSTRAINT question_response_datetime_response_fkey FOREIGN KEY (response)
        REFERENCES surveys.question_response (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS surveys.question_response_datetime
    OWNER to wolfy;

GRANT ALL ON TABLE surveys.question_response_datetime TO wolfy;

GRANT SELECT, DELETE, INSERT, UPDATE ON TABLE surveys.question_response_datetime TO survey_wolf_bot;

GRANT ALL ON TABLE surveys.question_response_datetime TO wolfy;
CREATE TABLE IF NOT EXISTS surveys.question_response_text
(
    text character varying COLLATE pg_catalog."default" NOT NULL,
    response integer NOT NULL,
    CONSTRAINT question_response_text_pkey PRIMARY KEY (response),
    CONSTRAINT question_response_text_response_fkey FOREIGN KEY (response)
        REFERENCES surveys.question_response (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS surveys.question_response_text
    OWNER to wolfy;

GRANT ALL ON TABLE surveys.question_response_text TO wolfy;

GRANT SELECT, DELETE, INSERT, UPDATE ON TABLE surveys.question_response_text TO survey_wolf_bot;

GRANT ALL ON TABLE surveys.question_response_text TO wolfy;
CREATE TABLE IF NOT EXISTS surveys.question_response_multiple_choice
(
    response integer NOT NULL,
    selected integer[] NOT NULL,
    CONSTRAINT question_response_multiple_choice_pkey PRIMARY KEY (response),
    CONSTRAINT question_response_multiple_choice_response_fkey FOREIGN KEY (response)
        REFERENCES surveys.question_response (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS surveys.question_response_multiple_choice
    OWNER to wolfy;

GRANT ALL ON TABLE surveys.question_response_multiple_choice TO wolfy;

GRANT SELECT, DELETE, INSERT, UPDATE ON TABLE surveys.question_response_multiple_choice TO survey_wolf_bot;

GRANT ALL ON TABLE surveys.question_response_multiple_choice TO wolfy;
REVOKE ALL ON TABLE surveys.question_response FROM survey_wolf_bot;
REVOKE ALL ON TABLE surveys.question_response FROM wolfy;
GRANT INSERT, SELECT, UPDATE, DELETE ON TABLE surveys.question_response TO survey_wolf_bot;

GRANT ALL ON TABLE surveys.question_response TO wolfy;

ALTER TABLE IF EXISTS surveys.question_response DROP CONSTRAINT IF EXISTS question_response_responses_id_fk;

ALTER TABLE IF EXISTS surveys.question_response
    ADD CONSTRAINT question_response_responses_id_fk FOREIGN KEY (response)
    REFERENCES surveys.responses (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS fki_question_response_responses_id_fk
    ON surveys.question_response USING btree
    (response ASC NULLS LAST)
    TABLESPACE pg_default;

DROP TRIGGER IF EXISTS validate_response_data ON surveys.question_response;
REVOKE ALL ON TABLE surveys.questions FROM survey_wolf_bot;
REVOKE ALL ON TABLE surveys.questions FROM wolfy;
GRANT INSERT, SELECT, UPDATE, DELETE ON TABLE surveys.questions TO survey_wolf_bot;

GRANT ALL ON TABLE surveys.questions TO wolfy;
DROP TRIGGER IF EXISTS validate_question_data ON surveys.questions;
ALTER TABLE IF EXISTS surveys.data_sharing_consent
    OWNER TO wolfy;

GRANT SELECT, INSERT, UPDATE ON TABLE surveys.data_sharing_consent TO survey_wolf_bot;

GRANT ALL ON TABLE surveys.data_sharing_consent TO wolfy;
REVOKE ALL ON TABLE surveys.active_guild_surveys FROM survey_wolf_bot;
REVOKE ALL ON TABLE surveys.active_guild_surveys FROM wolfy;
GRANT INSERT, SELECT, UPDATE, DELETE ON TABLE surveys.active_guild_surveys TO survey_wolf_bot;

GRANT ALL ON TABLE surveys.active_guild_surveys TO wolfy;
REVOKE ALL ON TABLE surveys.responses FROM survey_wolf_bot;
REVOKE ALL ON TABLE surveys.responses FROM wolfy;
GRANT INSERT, SELECT, UPDATE, DELETE ON TABLE surveys.responses TO survey_wolf_bot;

GRANT ALL ON TABLE surveys.responses TO wolfy;
REVOKE ALL ON TABLE surveys.template FROM survey_wolf_bot;
REVOKE ALL ON TABLE surveys.template FROM wolfy;
GRANT INSERT, SELECT, UPDATE, DELETE ON TABLE surveys.template TO survey_wolf_bot;

GRANT ALL ON TABLE surveys.template TO wolfy;


-- This Was Not Generated. It Converts The Existing Data Away From JSONB
INSERT INTO surveys.question_response_text (text, response)
    SELECT COALESCE(question_response.response_data->>'text', ''), question_response.id
    FROM surveys.question_response JOIN surveys.questions ON questions.id = question_response.question
    WHERE questions.type = 0;
INSERT INTO surveys.question_response_multiple_choice (selected, response)
    SELECT
        ARRAY(SELECT jsonb_array_elements_text(COALESCE(question_response.response_data->'selected', '[]'::jsonb))::int),
        question_response.id
    FROM surveys.question_response JOIN surveys.questions ON questions.id = question_response.question
    WHERE questions.type = 1;
INSERT INTO surveys.question_response_datetime ("timestamp", response)
    SELECT question_response.response_data->'timestamp', question_response.id
    FROM surveys.question_response JOIN surveys.questions ON questions.id = question_response.question
    WHERE questions.type = 2;


INSERT INTO surveys.question_text (min_length, max_length, "id")
    SELECT COALESCE((question_data->>'min_length')::int, 0), COALESCE((question_data->>'max_length')::int, 4000), "id"
    FROM surveys.questions
    WHERE questions.type = 0;
INSERT INTO surveys.question_multiple_choice (min_selects, max_selects, options, "id")
    SELECT
        COALESCE((question_data->>'min_selects')::int, 1),
        COALESCE((question_data->>'max_selects')::int, 1),
        ARRAY[]::int[],
        "id"
    FROM surveys.questions
    WHERE questions.type = 1;
INSERT INTO surveys.question_multiple_choice_option (text, position, question_id)
	SELECT
	    opt.jb->>'text',
	    opt.idx - 1,
	    q.id
	FROM surveys.questions q,
	     jsonb_array_elements(q.question_data->'options') WITH ORDINALITY AS opt(jb, idx)
	WHERE q.type = 1;
INSERT INTO surveys.question_datetime ("type", minimum, maximum, "id")
    SELECT
        COALESCE((question_data->>'type')::int, 0),
        COALESCE(question_data->>'minimum', ''),
        COALESCE(question_data->>'maximum', ''),
        "id"
    FROM surveys.questions
    WHERE questions.type = 2;


 END;